### ISSUE TITLE
(Don't?) Use tuple sections

### ISSUE THREAD

**Issue by codygman** [EdutainmentLIVE/haskell-style-guide#49] opened 2019-05-15 14:16 UTC
Just to make cases like a `Map (Maybe key) value` where you only need keys that exist easier:

```
mapMaybe (\(mk, a) -> case mk of Just k -> Just (k, a); Nothing -> Nothing) [(Just "key 1", 0), (Nothing, 1)]
```

without tuple sections you may arrive at:

```
mapMaybe (\(mk, a) -> fmap (flip (,) a) mk)
```

With tuple sections, that becomes:

```
mapMaybe (\(mk, a) -> fmap (,a) mk) 
```

But maybe this should have been done:

```
mapMaybe (\(mk, a) -> fmap (\key -> (key, a)) mk)
```

Maybe I made a better argument for not using tuple sections :)

**Comment by tfausak** [comment] 2019-05-15 14:25
I'm not a fan of tuple sections. They feel similar to lambda case for me: A nice syntactic convenience for avoiding variable names. I generally don't mind coming up with variable names. I prefer there to be less syntax overall too. I like the last option the best:

``` hs
f :: [(Maybe k, v)] -> [(k, v)]
f = Maybe.mapMaybe (\ (mk, v) -> fmap (\ k -> (k, v)) mk)
```

**Comment by tfausak** [comment] 2019-07-08 17:42
Is this any different than #13? I don't want to make separate things for each language extension that we don't want to use 😛

**Comment by tfausak** [comment] 2021-06-15 13:12
I'm going to close this one as a duplicate of #13.

**Closed by tfausak** 2021-06-15 13:12 UTC
Labels: enhancement, question
